version: '2'
services:
  nginx:
    image: nginx
    restart: always
    ports:
        - "5011:8080"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./dist:/usr/share/nginx/html
    depends_on:
      - bmsserver
  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:
      KAFKA_CREATE_TOPICS: "BMS.bms:2:2,BMS.position:2:2"
      KAFKA_ADVERTISED_HOST_NAME: 114.55.89.241
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  bmsserver:
    image: node:6.11.2
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./restfulsrv:/app
    environment:
      - MONGO_URL=mongodb://192.168.0.1:27018/bms
      - listenport=5012
    links:
      - mongodb
    ports:
       - "5012:5012"
    expose:
       - "5012"
  mongodb:
    image:  mongo:3.4
    expose:
       - "27018"
    volumes:
       - "/var/db100/dbdata:/data/db -d"
    ports:
       - "27018:27018"
